const sb=document.getElementById('sb'),mn=document.getElementById('main'),tg=document.getElementById('tog'),bk=document.getElementById('bk');
if(tg)tg.onclick=()=>{if(innerWidth<992){sb.classList.toggle('mobile-open');bk.classList.toggle('show')}};
if(bk)bk.onclick=()=>{sb.classList.remove('mobile-open');bk.classList.remove('show')};
if(typeof Chart!=='undefined'){Chart.defaults.font.family="'Inter',sans-serif";Chart.defaults.color='#6B7385'}
const wE=document.getElementById('wChart');
if(wE){const ctx=wE.getContext('2d');const g=ctx.createLinearGradient(0,0,0,280);g.addColorStop(0,'rgba(91,84,232,.22)');g.addColorStop(1,'rgba(91,84,232,0)');new Chart(wE,{type:'line',data:{labels:window.wL||[],datasets:[{data:window.wD||[],borderColor:'#5B54E8',backgroundColor:g,borderWidth:3,tension:.42,fill:true,pointBackgroundColor:'#fff',pointBorderColor:'#5B54E8',pointBorderWidth:2.5,pointRadius:4,pointHoverRadius:7,pointHoverBorderWidth:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{backgroundColor:'#0B1020',padding:12,cornerRadius:10,displayColors:false,titleFont:{size:12,weight:'600'},bodyFont:{size:13},callbacks:{label:c=>c.parsed.y+'% present'}}},scales:{y:{beginAtZero:true,max:100,border:{display:false},grid:{color:'#F1F2F6'},ticks:{callback:v=>v+'%',font:{size:11},padding:8}},x:{border:{display:false},grid:{display:false},ticks:{font:{size:11},padding:6}}}}})}
const pE=document.getElementById('pChart');
if(pE){const r=window.aR||0;new Chart(pE,{type:'doughnut',data:{datasets:[{data:[r,100-r],backgroundColor:['#5B54E8','#ECEEF3'],borderWidth:0,borderRadius:6,spacing:2}]},options:{responsive:true,maintainAspectRatio:false,cutout:'78%',plugins:{legend:{display:false},tooltip:{enabled:false}}}})}
document.querySelectorAll('[data-confirm]').forEach(e=>e.onclick=ev=>{if(!confirm(e.dataset.confirm))ev.preventDefault()});
